[tool.poetry]
name = "pazu"
version = "0.1.0"
description = ""
authors = ["Itani"]

[tool.poetry.dependencies]
python = "^3.7"
pygame = {version = "^1.9", allows-prereleases = true}
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
